# Generated by Django 4.0.5 on 2022-08-19 08:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('presale', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('cashback', models.IntegerField()),
                ('acceptedToken', models.CharField(default='0x0', max_length=42)),
                ('ownerAddress', models.CharField(max_length=42)),
                ('managerContract', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('name', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=5)),
                ('supply', models.IntegerField()),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EventApp.event')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('userAddres', models.CharField(max_length=42)),
                ('txHash', models.CharField(max_length=64)),
                ('items_payed', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('items_redeemed', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('fulfilled', models.BooleanField(default=False)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0.0)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EventApp.event')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0.0)),
                ('desciption', models.TextField(default='')),
                ('shoppingList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventApp.shoppinglist')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='EventApp.token'),
        ),
        migrations.AddField(
            model_name='event',
            name='vendor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='EventApp.vendor'),
        ),
    ]
