# Generated by Django 4.0.5 on 2022-08-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desciption',
            new_name='description',
        ),
    ]
