# Generated by Django 4.0.5 on 2022-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_rename_useraddres_order_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items_payed',
            new_name='itemsPayed',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='items_redeemed',
            new_name='itemsRedeemed',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=64),
        ),
    ]
