# Generated by Django 4.0.5 on 2022-08-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0004_rename_items_payed_order_itemspayed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='txHash',
            field=models.CharField(max_length=66),
        ),
    ]
